"""Changed numeric data types to allow better data representation

Revision ID: 19089cd961e8
Revises: 35c7e94e6883
Create Date: 2015-07-23 12:06:07.423576

"""

# revision identifiers, used by Alembic.
revision = '19089cd961e8'
down_revision = '35c7e94e6883'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('density_data', 'density',
               existing_type=mysql.DECIMAL(precision=10, scale=8),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('parameters', 'DomainSize',
               existing_type=mysql.DECIMAL(precision=19, scale=4),
               type_=sa.Numeric(precision=19, scale=7),
               existing_nullable=False)
    op.alter_column('parameters', 'R',
               existing_type=mysql.DECIMAL(precision=19, scale=4),
               type_=sa.Numeric(precision=19, scale=7),
               existing_nullable=False)
    op.alter_column('parameters', 'diffusion_coeff',
               existing_type=mysql.DECIMAL(precision=19, scale=4),
               type_=sa.Numeric(precision=19, scale=7),
               existing_nullable=False)
    op.alter_column('parameters', 'drift_coeff',
               existing_type=mysql.DECIMAL(precision=19, scale=4),
               type_=sa.Numeric(precision=19, scale=7),
               existing_nullable=False)
    op.alter_column('parameters', 'ic_p',
               existing_type=mysql.DECIMAL(precision=19, scale=4),
               type_=sa.Numeric(precision=19, scale=7),
               existing_nullable=False)
    op.alter_column('parameters', 'omega_p',
               existing_type=mysql.DECIMAL(precision=19, scale=4),
               type_=sa.Numeric(precision=19, scale=7),
               existing_nullable=False)
    op.alter_column('parameters', 'u0',
               existing_type=mysql.DECIMAL(precision=19, scale=4),
               type_=sa.Numeric(precision=19, scale=7),
               existing_nullable=False)
    op.alter_column('path_meta_data', 'stochastic',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('path_meta_data', 'time',
               existing_type=mysql.DECIMAL(precision=20, scale=9),
               type_=sa.Numeric(precision=24, scale=14),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('path_meta_data', 'time',
               existing_type=sa.Numeric(precision=24, scale=14),
               type_=mysql.DECIMAL(precision=20, scale=9),
               existing_nullable=False)
    op.alter_column('path_meta_data', 'stochastic',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('parameters', 'u0',
               existing_type=sa.Numeric(precision=19, scale=7),
               type_=mysql.DECIMAL(precision=19, scale=4),
               existing_nullable=False)
    op.alter_column('parameters', 'omega_p',
               existing_type=sa.Numeric(precision=19, scale=7),
               type_=mysql.DECIMAL(precision=19, scale=4),
               existing_nullable=False)
    op.alter_column('parameters', 'ic_p',
               existing_type=sa.Numeric(precision=19, scale=7),
               type_=mysql.DECIMAL(precision=19, scale=4),
               existing_nullable=False)
    op.alter_column('parameters', 'drift_coeff',
               existing_type=sa.Numeric(precision=19, scale=7),
               type_=mysql.DECIMAL(precision=19, scale=4),
               existing_nullable=False)
    op.alter_column('parameters', 'diffusion_coeff',
               existing_type=sa.Numeric(precision=19, scale=7),
               type_=mysql.DECIMAL(precision=19, scale=4),
               existing_nullable=False)
    op.alter_column('parameters', 'R',
               existing_type=sa.Numeric(precision=19, scale=7),
               type_=mysql.DECIMAL(precision=19, scale=4),
               existing_nullable=False)
    op.alter_column('parameters', 'DomainSize',
               existing_type=sa.Numeric(precision=19, scale=7),
               type_=mysql.DECIMAL(precision=19, scale=4),
               existing_nullable=False)
    op.alter_column('density_data', 'density',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=mysql.DECIMAL(precision=10, scale=8),
               existing_nullable=False)
    ### end Alembic commands ###
