"""init

Revision ID: 35c7e94e6883
Revises: 
Create Date: 2015-07-23 12:03:36.651365

"""

# revision identifiers, used by Alembic.
revision = '35c7e94e6883'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
